export const AUTHENTICATION__REQUEST = 'AUTHENTICATION__REQUEST';
export const UNAUTHENTICATE__SUCCESS = 'UNAUTHENTICATE__SUCCESS';
export const AUTHENTICATE__SUCCESS = 'AUTHENTICATE__SUCCESS';
export const AUTHENTICATION__FAILURE = 'AUTHENTICATION__FAILURE';

export const CHANNEL_CREATE = 'CHANNEL_CREATE';
export const CHANNEL_UPDATE = 'CHANNEL_UPDATE';
export const CHANNEL_DELETE = 'CHANNEL_DELETE';
export const CHANNEL_SELECT = 'CHANNEL_SELECT';
export const CHANNELS_REORDER = 'CHANNELS_REORDER';


export const CHANNELS_FETCH__REQUEST = 'CHANNELS_FETCH__REQUEST';
export const CHANNELS_FETCH__SUCCESS = 'CHANNELS_FETCH__SUCCESS';
export const CHANNELS_FETCH__FAILURE = 'CHANNELS_FETCH__FAILURE';
export const CHANNELS_POST__SUCCESS = 'CHANNELS_POST__SUCCESS';
export const CHANNELS_POST__FAILURE = 'CHANNELS_POST__FAILURE';
export const CHANNELS_DELETE__SUCCESS = 'CHANNELS_DELETE__SUCCESS';
export const CHANNELS_DELETE__FAILURE = 'CHANNELS_DELETE__FAILURE';
export const CHANNELS_UPDATE__SUCCESS = 'CHANNELS_UPDATE__SUCCESS';
export const CHANNELS_UPDATE__FAILURE = 'CHANNELS_UPDATE__FAILURE';
export const CHANNELS_REORDER__SUCCESS = 'CHANNELS_REORDER__SUCCESS';
export const CHANNELS_REORDER__FAILURE = 'CHANNELS_REORDER__FAILURE';
export const CHANNELS_ORDER_FETCH__REQUEST = 'CHANNELS_ORDER_FETCH__REQUEST';
export const CHANNELS_ORDER_FETCH__SUCCESS = 'CHANNELS_ORDER_FETCH__SUCCESS';
export const CHANNELS_ORDER_FETCH__FAILURE = 'CHANNELS_ORDER_FETCH__FAILURE';

export const MESSAGES_FETCH__REQUEST = 'MESSAGES_FETCH__REQUEST';
export const MESSAGES_FAKE_RECEIVE__REQUEST = 'MESSAGES_FAKE_RECEIVE__REQUEST';
export const MESSAGES_FETCH__SUCCESS = 'MESSAGES_FETCH__SUCCESS';
export const MESSAGES_FETCH__FAILURE = 'MESSAGES_FETCH__FAILURE';
export const MESSAGES_DELETE__SUCCESS = 'MESSAGES_DELETE__SUCCESS';
export const MESSAGES_DELETE__FAILURE = 'MESSAGES_DELETE__FAILURE';
export const MESSAGES_POST__SUCCESS = 'MESSAGES_POST__SUCCESS';
export const MESSAGES_POST__FAILURE = 'MESSAGES_POST__FAILURE';
export const MESSAGES_UPDATE__SUCCESS = 'MESSAGES_UPDATE__SUCCESS';
export const MESSAGES_UPDATE__FAILURE = 'MESSAGES_UPDATE__FAILURE';

export const MESSAGE_CREATE = 'MESSAGE_CREATE';
export const MESSAGE_DELETE = 'MESSAGE_DELETE';
export const MESSAGE_LIKE = 'MESSAGE_LIKE';
export const MESSAGE_DISLIKE = 'MESSAGE_DISLIKE';

export const USER_CHANGE_AVATAR = 'USER_CHANGE_AVATAR';
export const USER_CHANGE_USERNAME = 'USER_CHANGE_USERNAME';
export const USER_CREATE = 'USER_CREATE';

export const USER_UPDATE__SUCCESS = 'USER_UPDATE__SUCCESS';
export const USER_UPDATE__FAILURE = 'USER_UPDATE__FAILURE';
export const USER_POST__SUCCESS = 'USER_POST__SUCCESS';
export const USER_POST__FAILURE = 'USER_POST__FAILURE';
export const USERS_ALL_FETCH__REQUEST = 'USERS_ALL_FETCH__REQUEST';
export const USERS_ALL_FETCH__SUCCESS = 'USERS_ALL_FETCH__SUCCESS';
export const USERS_ALL_FETCH__FAILURE = 'USERS_ALL_FETCH__FAILURE';

export const FILE_UPLOAD__REQUEST = 'FILE_UPLOAD__REQUEST';
export const FILE_UPLOAD__SUCCESS = 'FILE_UPLOAD__SUCCESS';
export const FILE_UPLOAD__FAILURE = 'FILE_UPLOAD__FAILURE';

export const FILE_DOWNLOAD_LINK_FETCH__REQUEST = 'FILE_DOWNLOAD_LINK_FETCH__REQUEST';
export const FILE_DOWNLOAD_LINK_FETCH__SUCCESS = 'FILE_DOWNLOAD_LINK_FETCH__SUCCESS';
export const FILE_DOWNLOAD_LINK_FETCH__FAILURE = 'FILE_DOWNLOAD_LINK_FETCH__FAILURE';
