export const TODO_LIST_ITEM_CREATE = 'TODO_LIST_ITEM_CREATE';
export const TODO_LIST_ITEM_UPDATE = 'TODO_LIST_ITEM_UPDATE';
export const TODO_LIST_ITEM_DELETE = 'TODO_LIST_ITEM_DELETE';
export const TODO_LIST_ITEM_MOVE = 'TODO_LIST_ITEM_MOVE';
export const TODO_LIST_ITEM_START_EDITING = 'TODO_LIST_ITEM_START_EDITING';
export const TODO_LIST_ITEM_CANCEL_EDITING = 'TODO_LIST_ITEM_CANCEL_EDITING';
export const TODO_LIST_OPEN_CREATE_NEW_FORM = 'TODO_LIST_OPEN_CREATE_NEW_FORM';
export const TODO_LIST_CLOSE_CREATE_NEW_FORM = 'TODO_LIST_CLOSE_CREATE_NEW_FORM';
export const TODO_LIST_ITEM_START_DRAGGING = 'TODO_LIST_ITEM_START_DRAGGING';
export const TODO_LIST_ITEM_STOP_DRAGGING = 'TODO_LIST_ITEM_STOP_DRAGGING';
export const TODO_LIST_SAVING_STARTED = 'TODO_LIST_SAVING_STARTED';
export const TODO_LIST_SAVING_FINISHED = 'TODO_LIST_SAVING_FINISHED';

export const PROFILE_UPDATE_DETAILS = 'PROFILE_UPDATE_DETAILS';
export const PROFILE_UPDATE_AVATAR = 'PROFILE_UPDATE_AVATAR';
export const PROFILE_FETCHING_STARTED = 'PROFILE_FETCHING_STARTED';
export const PROFILE_FETCHING_FAILED = 'PROFILE_FETCHING_FAILED';
export const PROFILE_UPLOADING_FAILED = 'PROFILE_UPLOADING_FAILED';
export const PROFILE_AVATAR_UPLOADING_STARTED = 'PROFILE_AVATAR_UPLOADING_STARTED';
export const PROFILE_AVATAR_UPLOADING_FAILED = 'PROFILE_AVATAR_UPLOADING_FAILED';
export const PROFILE_AVATAR_FETCHING_STARTED = 'PROFILE_AVATAR_FETCHING_STARTED';
export const PROFILE_AVATAR_FETCHING_FAILED = 'PROFILE_AVATAR_FETCHING_FAILED';

export const SHARED_RECEIVE_TOKEN = 'SHARED_RECEIVE_TOKEN';
export const SHARED_INVALIDATE_TOKEN = 'SHARED_INVALIDATE_TOKEN';
export const SHARED_AUTHENTICATION_STARTED = 'SHARED_AUTHENTICATION_STARTED';
export const SHARED_AUTHENTICATION_FAILED = 'SHARED_AUTHENTICATION_FAILED';
export const SHARED_DISMISS_ERROR = 'SHARED_DISMISS_ERROR';
